import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const PACKAGE = new URL('../tools/v2_r1_helius_handoff/step16_identity_header_review/', import.meta.url);
const GENERATOR = new URL('./generate_owner_header.mjs', PACKAGE);
const EVIDENCE = new URL('./canonical_owner_evidence.txt', PACKAGE);
const REVIEW_HEADER = new URL('./generated_owner_config.review.h', PACKAGE);
const REVIEW = new URL('../docs/operations/v2-r1-step16-identity-header-review.md', import.meta.url);
const ACTIVE_PLACEHOLDER = new URL('../tools/v2_r1_helius_handoff/generated_owner_config.h', import.meta.url);
const NATIVE_WRAPPER = new URL('../tools/v2_r1_helius_handoff/native_wrapper.c', import.meta.url);

const EXPECTED_ACTIVE_PLACEHOLDER = [
  '/*',
  ' * Repository safety placeholder.',
  ' *',
  ' * This fixed-path file is intentionally not an identity configuration and must',
  ' * never produce a production executable. A separately authorized generator may',
  ' * replace it only after validating canonical decimal UID/GID facts and making',
  ' * the generated bytes and permissions available for independent review.',
  ' */',
  '#error "authorized generated owner configuration is required; repository placeholder selects no identity"',
  '',
].join('\n');

const EXPECTED_EVIDENCE = [
  'report_classification=user-reported-not-current-host-authority',
  'source=reported',
  'owner_uid=1001',
  'owner_gid=1001',
  'home=directory,uid=0,gid=0,mode=0755',
  'piadmin=directory,uid=1001,gid=1001,mode=0700',
  'config=directory,uid=1001,gid=1001,mode=0700',
  'cumzillaraptors=directory,uid=1001,gid=1001,mode=0700',
  'secret_file=regular,uid=1001,gid=1001,mode=0600',
  'symlink_indicator=absent',
].join('\n') + '\n';

const EXPECTED_HEADER = [
  '#ifndef HELIUS_HANDOFF_GENERATED_OWNER_CONFIG_REVIEW_H',
  '#define HELIUS_HANDOFF_GENERATED_OWNER_CONFIG_REVIEW_H',
  '',
  '#define HELIUS_HANDOFF_GENERATED_OWNER_UID 1001',
  '#define HELIUS_HANDOFF_GENERATED_OWNER_GID 1001',
  '',
  '#endif /* HELIUS_HANDOFF_GENERATED_OWNER_CONFIG_REVIEW_H */',
  '',
].join('\n');

const sha256 = (value) => createHash('sha256').update(value, 'utf8').digest('hex');
const {
  LINUX_UID_GID_MAX,
  assertNoUserMacroDefinitions,
  generateOwnerHeader,
  parseCanonicalEvidence,
  parseLinuxUidGid,
} = await import(GENERATOR.href);

test('Step16 canonical evidence has the sole fixed grammar, source classification, exact final LF, and Linux uid_t/gid_t bounds', async () => {
  const evidence = await readFile(EVIDENCE, 'utf8');
  assert.equal(evidence, EXPECTED_EVIDENCE);
  assert.deepEqual(parseCanonicalEvidence(evidence), Object.freeze({ uid: 1001, gid: 1001 }));
  assert.equal(LINUX_UID_GID_MAX, 4294967295);
  assert.equal(parseLinuxUidGid('0'), 0);
  assert.equal(parseLinuxUidGid('4294967295'), 4294967295);
  for (const value of ['00', '01001', '+1001', '-1', '1+1', '1001 ', ' 1001', '4294967296', '1\n', '']) {
    assert.throws(() => parseLinuxUidGid(value), /canonical decimal Linux uid_t\/gid_t/);
  }
});

test('Step16 generator produces exact review-only header bytes from canonical non-secret evidence', async () => {
  const evidence = await readFile(EVIDENCE, 'utf8');
  assert.equal(generateOwnerHeader(evidence), EXPECTED_HEADER);
  assert.equal(await readFile(REVIEW_HEADER, 'utf8'), EXPECTED_HEADER);
  const directives = EXPECTED_HEADER.match(/^#(?:if|ifndef|define|endif|include|undef|error|pragma)\b.*$/gm) ?? [];
  assert.deepEqual(directives, [
    '#ifndef HELIUS_HANDOFF_GENERATED_OWNER_CONFIG_REVIEW_H',
    '#define HELIUS_HANDOFF_GENERATED_OWNER_CONFIG_REVIEW_H',
    '#define HELIUS_HANDOFF_GENERATED_OWNER_UID 1001',
    '#define HELIUS_HANDOFF_GENERATED_OWNER_GID 1001',
    '#endif /* HELIUS_HANDOFF_GENERATED_OWNER_CONFIG_REVIEW_H */',
  ]);
  assert.match(EXPECTED_HEADER, /^#define HELIUS_HANDOFF_GENERATED_OWNER_UID 1001$/m);
  assert.match(EXPECTED_HEADER, /^#define HELIUS_HANDOFF_GENERATED_OWNER_GID 1001$/m);
  assert.doesNotMatch(EXPECTED_HEADER, /HELIUS_HANDOFF_GENERATED_OWNER_(?:UID|GID)\s+(?!1001$).+/m);
});

test('Step16 rejects noncanonical evidence and hostile user macro input before header construction', () => {
  const mutations = [
    EXPECTED_EVIDENCE.replace('owner_uid=1001', 'owner_uid=1+1000'),
    EXPECTED_EVIDENCE.replace('owner_uid=1001', 'owner_uid=01001'),
    EXPECTED_EVIDENCE.replace('owner_uid=1001', 'owner_uid=1001 '),
    EXPECTED_EVIDENCE.replace('owner_uid=1001', 'owner_uid=4294967296'),
    EXPECTED_EVIDENCE.replace('owner_gid=1001', 'owner_gid=1002'),
    EXPECTED_EVIDENCE.replace('home=directory,uid=0,gid=0,mode=0755\n', ''),
    EXPECTED_EVIDENCE.replace('secret_file=regular,uid=1001,gid=1001,mode=0600', 'secret_file=directory,uid=1001,gid=1001,mode=0600'),
    EXPECTED_EVIDENCE.replace('config=directory,uid=1001,gid=1001,mode=0700', 'config=directory,uid=1001,gid=1001,mode=0755'),
    EXPECTED_EVIDENCE.replace('symlink_indicator=absent', 'symlink_indicator=present'),
    EXPECTED_EVIDENCE.replace('source=reported', 'source=observed'),
    EXPECTED_EVIDENCE.replace('report_classification=user-reported-not-current-host-authority', 'report_classification=current-host-authority'),
    EXPECTED_EVIDENCE.replace('owner_uid=1001\nowner_gid=1001', 'owner_gid=1001\nowner_uid=1001'),
    EXPECTED_EVIDENCE.replace('symlink_indicator=absent\n', 'symlink_indicator=absent\nunknown=value\n'),
    EXPECTED_EVIDENCE.slice(0, -1),
    EXPECTED_EVIDENCE.replace('owner_uid=1001', 'owner_uid=1001\nowner_uid=1001'),
  ];
  for (const evidence of mutations) assert.throws(() => generateOwnerHeader(evidence), /canonical evidence/);

  for (const macros of [
    '-DHELIUS_HANDOFF_GENERATED_OWNER_UID=0',
    { HELIUS_HANDOFF_GENERATED_OWNER_UID: '1001' },
    ['HELIUS_HANDOFF_GENERATED_OWNER_GID=1001'],
    '#define HELIUS_HANDOFF_GENERATED_OWNER_UID 1001\n#include </etc/passwd>',
  ]) {
    assert.throws(() => assertNoUserMacroDefinitions(macros), /user macro definitions are forbidden/);
    assert.throws(() => generateOwnerHeader(EXPECTED_EVIDENCE, macros), /exactly one canonical evidence argument is required/);
    assert.throws(
      () => generateOwnerHeader(EXPECTED_EVIDENCE, undefined, macros),
      /exactly one canonical evidence argument is required/,
    );
  }
});

test('Step16 active identity boundary remains the exact fail-closed placeholder and direct native include', async () => {
  const [placeholder, nativeWrapper] = await Promise.all([
    readFile(ACTIVE_PLACEHOLDER, 'utf8'), readFile(NATIVE_WRAPPER, 'utf8'),
  ]);
  assert.equal(placeholder, EXPECTED_ACTIVE_PLACEHOLDER);
  assert.equal(sha256(placeholder), 'bd19ffa281f81e12e7c49327b81f0c801097c9a5af8d233cf84d175231b48233');
  assert.deepEqual(
    nativeWrapper.match(/^#include "generated_owner_config\.h"$/gm) ?? [],
    ['#include "generated_owner_config.h"'],
  );
});

test('Step16 review document binds evidence and header SHA-256 bytes and states the repository-only capability boundary', async () => {
  const [evidence, header, review, generatorSource] = await Promise.all([
    readFile(EVIDENCE, 'utf8'), readFile(REVIEW_HEADER, 'utf8'), readFile(REVIEW, 'utf8'), readFile(GENERATOR, 'utf8'),
  ]);
  assert.ok(review.includes(`canonical evidence SHA-256: \`${sha256(evidence)}\``));
  assert.ok(review.includes(`review header SHA-256: \`${sha256(header)}\``));
  for (const phrase of [
    'user-reported and not current host authority',
    'review artifact only',
    'does not authorize modifying the active placeholder',
    'does not authorize usable wrapper compilation or execution',
    'does not authorize endpoint read, RPC, signing, sending, or deployment',
    'no CLI, environment, configuration, secret discovery, host access, network, RPC, compilation, or execution',
  ]) assert.match(review, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'));
  assert.doesNotMatch(generatorSource, /(?:from|import\()\s*['"]node:(?:fs|child_process|net|http|https|tls|os)['"]/);
  assert.doesNotMatch(generatorSource, /(?<!\.)\b(?:readFile|writeFile|spawn(?:Sync)?|exec(?:Sync|File)?|fetch)\s*\(|process\.(?:env|argv)\b/);
});

// Repository-text and pure-value tests only: no /home/piadmin access, secret read, compiler/process launch, RPC/network, signing, sending, or deployment.
