#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#ifndef STEP16_DESCRIPTOR_HELPER_REVIEW_FIXTURE
#error "Step16 descriptor helper is review-only; a future authorized production configuration is required."
#endif

#include "descriptor_helper.h"

#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

struct sha256_state { uint32_t h[8]; uint64_t bits; unsigned char block[64]; size_t used; };
static uint32_t ror32(uint32_t x, unsigned int n) { return (x >> n) | (x << (32U - n)); }
static const uint32_t k[64] = { 0x428a2f98U,0x71374491U,0xb5c0fbcfU,0xe9b5dba5U,0x3956c25bU,0x59f111f1U,0x923f82a4U,0xab1c5ed5U,0xd807aa98U,0x12835b01U,0x243185beU,0x550c7dc3U,0x72be5d74U,0x80deb1feU,0x9bdc06a7U,0xc19bf174U,0xe49b69c1U,0xefbe4786U,0x0fc19dc6U,0x240ca1ccU,0x2de92c6fU,0x4a7484aaU,0x5cb0a9dcU,0x76f988daU,0x983e5152U,0xa831c66dU,0xb00327c8U,0xbf597fc7U,0xc6e00bf3U,0xd5a79147U,0x06ca6351U,0x14292967U,0x27b70a85U,0x2e1b2138U,0x4d2c6dfcU,0x53380d13U,0x650a7354U,0x766a0abbU,0x81c2c92eU,0x92722c85U,0xa2bfe8a1U,0xa81a664bU,0xc24b8b70U,0xc76c51a3U,0xd192e819U,0xd6990624U,0xf40e3585U,0x106aa070U,0x19a4c116U,0x1e376c08U,0x2748774cU,0x34b0bcb5U,0x391c0cb3U,0x4ed8aa4aU,0x5b9cca4fU,0x682e6ff3U,0x748f82eeU,0x78a5636fU,0x84c87814U,0x8cc70208U,0x90befffaU,0xa4506cebU,0xbef9a3f7U,0xc67178f2U };
static void sha_block(struct sha256_state *s, const unsigned char *p) { uint32_t w[64],a,b,c,d,e,f,g,h,t1,t2; size_t i; for(i=0;i<16;i++) w[i]=((uint32_t)p[4*i]<<24)|((uint32_t)p[4*i+1]<<16)|((uint32_t)p[4*i+2]<<8)|p[4*i+3]; for(i=16;i<64;i++){uint32_t x=w[i-15],y=w[i-2]; w[i]=w[i-16]+(ror32(x,7)^ror32(x,18)^(x>>3))+w[i-7]+(ror32(y,17)^ror32(y,19)^(y>>10));} a=s->h[0];b=s->h[1];c=s->h[2];d=s->h[3];e=s->h[4];f=s->h[5];g=s->h[6];h=s->h[7]; for(i=0;i<64;i++){t1=h+(ror32(e,6)^ror32(e,11)^ror32(e,25))+((e&f)^((~e)&g))+k[i]+w[i];t2=(ror32(a,2)^ror32(a,13)^ror32(a,22))+((a&b)^(a&c)^(b&c));h=g;g=f;f=e;e=d+t1;d=c;c=b;b=a;a=t1+t2;} s->h[0]+=a;s->h[1]+=b;s->h[2]+=c;s->h[3]+=d;s->h[4]+=e;s->h[5]+=f;s->h[6]+=g;s->h[7]+=h; }
static void sha_init(struct sha256_state *s){static const uint32_t v[8]={0x6a09e667U,0xbb67ae85U,0x3c6ef372U,0xa54ff53aU,0x510e527fU,0x9b05688cU,0x1f83d9abU,0x5be0cd19U}; memcpy(s->h,v,sizeof v);s->bits=0;s->used=0;}
static void sha_add(struct sha256_state *s,const unsigned char *p,size_t n){while(n){size_t take=64-s->used;if(take>n)take=n;memcpy(s->block+s->used,p,take);s->used+=take;p+=take;n-=take;if(s->used==64){sha_block(s,s->block);s->bits+=512;s->used=0;}}}
static void sha_end(struct sha256_state *s,unsigned char out[32]){size_t i;s->bits+=(uint64_t)s->used*8U;s->block[s->used++]=0x80; if(s->used>56){while(s->used<64)s->block[s->used++]=0;sha_block(s,s->block);s->used=0;}while(s->used<56)s->block[s->used++]=0;for(i=0;i<8;i++)s->block[63-i]=(unsigned char)(s->bits>>(8*i));sha_block(s,s->block);for(i=0;i<8;i++){out[4*i]=(unsigned char)(s->h[i]>>24);out[4*i+1]=(unsigned char)(s->h[i]>>16);out[4*i+2]=(unsigned char)(s->h[i]>>8);out[4*i+3]=(unsigned char)s->h[i];}}
static int hex_digest(const unsigned char *bytes,size_t length,const char *hex){static const char x[]="0123456789abcdef";unsigned char digest[32];char result[65];size_t i;struct sha256_state s;sha_init(&s);sha_add(&s,bytes,length);sha_end(&s,digest);for(i=0;i<32;i++){result[2*i]=x[digest[i]>>4];result[2*i+1]=x[digest[i]&15U];}result[64]='\0';return strcmp(result,hex)==0;}
static int safe_opaque(const struct step16_opaque_id *id){size_t i;if(!id||id->length==0||id->length>STEP16_OPAQUE_ID_CAP)return 0;for(i=0;i<id->length;i++)if(!((id->bytes[i]>='a'&&id->bytes[i]<='z')||(id->bytes[i]>='A'&&id->bytes[i]<='Z')||(id->bytes[i]>='0'&&id->bytes[i]<='9')||id->bytes[i]=='_'||id->bytes[i]=='-'))return 0;return 1;}
static int make_stage_name(char stage[sizeof "build-stage-" + STEP16_OPAQUE_ID_CAP],const struct step16_opaque_id *id){static const char prefix[]="build-stage-";if(!safe_opaque(id))return 0;memcpy(stage,prefix,sizeof prefix-1);memcpy(stage+sizeof prefix-1,id->bytes,id->length);stage[sizeof prefix-1+id->length]='\0';return 1;}
static ssize_t real_write(int fd,const void *b,size_t n,void *unused){(void)unused;return write(fd,b,n);}
static int real_close(int fd,void *unused){(void)unused;return close(fd);}
static int real_unlinkat(int fd,const char *name,int flags,void *unused){(void)unused;return unlinkat(fd,name,flags);}
static int close_checked(const struct step16_descriptor_ops *ops,int fd){return ops&&ops->close_fd?ops->close_fd(fd,ops->context):real_close(fd,NULL);}
static int unlink_checked(const struct step16_descriptor_ops *ops,int fd,const char *name,int flags){return ops&&ops->unlink_entry?ops->unlink_entry(fd,name,flags,ops->context):real_unlinkat(fd,name,flags,NULL);}
static int write_exact(int fd,const unsigned char *p,size_t n,step16_write_fn writer,void *context){size_t done=0;while(done<n){ssize_t got=writer(fd,p+done,n-done,context);if(got<=0||(size_t)got>n-done)return 0;done+=(size_t)got;}return 1;}
static int verify_held(int fd,size_t expected,const char *digest){struct stat st;unsigned char buffer[1024];struct sha256_state state;unsigned char actual[32];char hex[65];size_t i;ssize_t got;if(fstat(fd,&st)!=0||!S_ISREG(st.st_mode)||(uintmax_t)st.st_size!=(uintmax_t)expected||lseek(fd,0,SEEK_SET)<0)return 0;sha_init(&state);while((got=read(fd,buffer,sizeof buffer))>0)sha_add(&state,buffer,(size_t)got);if(got<0)return 0;sha_end(&state,actual);for(i=0;i<32;i++){static const char chars[]="0123456789abcdef";hex[2*i]=chars[actual[i]>>4];hex[2*i+1]=chars[actual[i]&15U];}hex[64]='\0';return strcmp(hex,digest)==0;}
static int stage_one(int stage_fd,const char *name,const unsigned char *bytes,size_t length,const char *digest,step16_write_fn writer,void *context,const struct step16_descriptor_ops *ops,int *cleanup_failed){int fd=openat(stage_fd,name,O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC,0600);int ok=0;if(fd<0)return 0;if(write_exact(fd,bytes,length,writer,context)&&verify_held(fd,length,digest))ok=1;if(close_checked(ops,fd)!=0){*cleanup_failed=1;ok=0;}return ok;}
enum step16_descriptor_status step16_stage_descriptor_pinned_sources(const struct step16_descriptor_request *r){char stage[sizeof "build-stage-" + STEP16_OPAQUE_ID_CAP];struct step16_authenticated_blob blob={0};struct step16_opaque_id issued={{0},0,NULL};step16_write_fn writer;int stage_fd=-1,created=0,cleanup_failed=0;enum step16_descriptor_status status=STEP16_DESCRIPTOR_REJECTED;if(!r||r->trusted_parent_fd<0||!r->read_native_wrapper||!r->issue_opaque_id||!r->opaque_issuer_context||!r->review_header_bytes)return status;if(r->issue_opaque_id(r->opaque_issuer_context,&issued)!=0||issued.issuer_tag!=r->opaque_issuer_context||!make_stage_name(stage,&issued))return status;if(mkdirat(r->trusted_parent_fd,stage,0700)!=0)return STEP16_DESCRIPTOR_IO;created=1;stage_fd=openat(r->trusted_parent_fd,stage,O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);if(stage_fd<0){status=STEP16_DESCRIPTOR_IO;goto cleanup;}if(r->after_stage_created&&r->after_stage_created(stage_fd,r->after_stage_context)!=0)goto cleanup;if(r->read_native_wrapper(r->reader_context,STEP16_EXPECTED_COMMIT,&blob)!=0||!blob.resolved_commit||strcmp(blob.resolved_commit,STEP16_EXPECTED_COMMIT)!=0||!blob.object_id||!blob.bytes||strcmp(blob.object_id,STEP16_NATIVE_WRAPPER_BLOB)!=0){status=STEP16_DESCRIPTOR_MISMATCH;goto cleanup;}if(!hex_digest(blob.bytes,blob.length,STEP16_NATIVE_WRAPPER_SHA256)||!hex_digest(r->review_header_bytes,r->review_header_length,STEP16_REVIEW_HEADER_SHA256)){status=STEP16_DESCRIPTOR_MISMATCH;goto cleanup;}writer=r->write_bytes?r->write_bytes:real_write;if(!stage_one(stage_fd,"native_wrapper.c",blob.bytes,blob.length,STEP16_NATIVE_WRAPPER_SHA256,writer,r->write_context,r->ops,&cleanup_failed)||!stage_one(stage_fd,"generated_owner_config.h",r->review_header_bytes,r->review_header_length,STEP16_REVIEW_HEADER_SHA256,writer,r->write_context,r->ops,&cleanup_failed)){status=STEP16_DESCRIPTOR_IO;goto cleanup;}status=STEP16_DESCRIPTOR_OK;cleanup:if(stage_fd>=0){if(unlink_checked(r->ops,stage_fd,"generated_owner_config.h",0)!=0&&errno!=ENOENT)cleanup_failed=1;if(unlink_checked(r->ops,stage_fd,"native_wrapper.c",0)!=0&&errno!=ENOENT)cleanup_failed=1;if(close_checked(r->ops,stage_fd)!=0)cleanup_failed=1;}if(created&&unlink_checked(r->ops,r->trusted_parent_fd,stage,AT_REMOVEDIR)!=0)cleanup_failed=1;if(cleanup_failed)return STEP16_DESCRIPTOR_CLEANUP_FAILED;return status;}
