/*
 * Repository safety placeholder.
 *
 * This fixed-path file is intentionally not an identity configuration and must
 * never produce a production executable. A separately authorized generator may
 * replace it only after validating canonical decimal UID/GID facts and making
 * the generated bytes and permissions available for independent review.
 */
#error "authorized generated owner configuration is required; repository placeholder selects no identity"
